# ESLint rule-set
# ===============
#
# The following rules are intended to be the least restrictive possible. Tweak
# them as much as you want, or simply replace this file with another one you
# have previously edited.
#
# Learn more about how to configure ESLint at
#   <http://eslint.org/docs/user-guide/configuring>.

env:
  es6: true                           # Enable ES2015+ features
  browser: true                       # Enable Browser global variables
  node: true
  jquery : true

parserOptions:
  ecmaVersion: 2016                   # Validate ECMAScript 2016 syntax
  sourceType: module                  # Allow ECMAScript modules

globals:
  PIXI: false
  Phaser: false
  module: false
  require: false
  process: false
  exports: false

extends: 'eslint:recommended'

rules:
  indent: [2, 2]                      # Indent code with 2 spaces
  quotes: [2, single]                 # Use single quotes for strings
  linebreak-style: [2, unix]          # Favor Unix-style line endings
  semi: [2, never]                   # End lines with semicolons

plugins: [node]
